# Generated by Django 5.1.4 on 2025-04-22 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='coverImage',
            field=models.ImageField(blank=True, upload_to='coverimages'),
        ),
        migrations.AddField(
            model_name='imageset',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
