# Generated by Django 5.1.4 on 2025-04-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imageset_coverimage_imageset_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='setname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='setname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.imageset'),
        ),
    ]
